/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import Gestion.GestionarHuespedes;
import Personas.Huesped;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author 20240
 */

public class InterfazGestionHuespedes extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazGestionHuespedes
     */
    private GestionarHuespedes gestionarHuespedes;
    
    public InterfazGestionHuespedes(GestionarHuespedes gestionarHuespedes) {
        initComponents();
        this.gestionarHuespedes = gestionarHuespedes;

        setTitle("Gestión de Huéspedes");
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private void limpiarFormularioHuesped() {
        txtIdHuesped.setText("");
        txtDniHuesped.setText("");
        txtNombresHuesped.setText("");
        txtApellidosHuesped.setText("");
        txtContactoHuesped.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.JPanel();
        btnModificarHuesped = new javax.swing.JButton();
        btnAgregarHuesped = new javax.swing.JButton();
        btnEliminarHuesped = new javax.swing.JButton();
        btnLimpiarHuesped = new javax.swing.JButton();
        btnMostrarHuespedes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblIdHuesped = new javax.swing.JLabel();
        lblDniHuesped = new javax.swing.JLabel();
        lblNombresHuesped = new javax.swing.JLabel();
        lblApellidosHuesped = new javax.swing.JLabel();
        lblContactoHuesped = new javax.swing.JLabel();
        txtIdHuesped = new javax.swing.JTextField();
        txtNombresHuesped = new javax.swing.JTextField();
        txtDniHuesped = new javax.swing.JTextField();
        txtApellidosHuesped = new javax.swing.JTextField();
        txtContactoHuesped = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Botones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnModificarHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModificarHuesped.setText("Modificar");
        btnModificarHuesped.addActionListener(this::btnModificarHuespedActionPerformed);

        btnAgregarHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarHuesped.setText("Agregar");
        btnAgregarHuesped.addActionListener(this::btnAgregarHuespedActionPerformed);

        btnEliminarHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminarHuesped.setText("Eliminar");
        btnEliminarHuesped.addActionListener(this::btnEliminarHuespedActionPerformed);

        btnLimpiarHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarHuesped.setText("Limpiar");
        btnLimpiarHuesped.addActionListener(this::btnLimpiarHuespedActionPerformed);

        btnMostrarHuespedes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarHuespedes.setText("Mostrar Huéspedes");
        btnMostrarHuespedes.addActionListener(this::btnMostrarHuespedesActionPerformed);

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BotonesLayout.createSequentialGroup()
                        .addComponent(btnAgregarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarHuesped)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMostrarHuespedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarHuesped)
                    .addComponent(btnModificarHuesped)
                    .addComponent(btnEliminarHuesped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarHuespedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnLimpiarHuesped))
        );

        lblIdHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdHuesped.setText("ID (solo para modificar o eliminar):");

        lblDniHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDniHuesped.setText("DNI:");

        lblNombresHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNombresHuesped.setText("Nombres");

        lblApellidosHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblApellidosHuesped.setText("Apellidos");

        lblContactoHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblContactoHuesped.setText("Contacto");

        txtIdHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdHuesped.addActionListener(this::txtIdHuespedActionPerformed);

        txtNombresHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDniHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtApellidosHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtContactoHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDniHuesped)
                    .addComponent(lblNombresHuesped)
                    .addComponent(lblApellidosHuesped)
                    .addComponent(lblContactoHuesped)
                    .addComponent(lblIdHuesped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactoHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombresHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdHuesped)
                    .addComponent(txtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniHuesped)
                    .addComponent(txtDniHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombresHuesped)
                    .addComponent(txtNombresHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosHuesped)
                    .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactoHuesped)
                    .addComponent(txtContactoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHuespedActionPerformed
        String idTexto = txtIdHuesped.getText().trim();
        String dni = txtDniHuesped.getText().trim();
        String nombres = txtNombresHuesped.getText().trim();
        String apellidos = txtApellidosHuesped.getText().trim();
        String contacto = txtContactoHuesped.getText().trim();

        if (idTexto.isEmpty() || dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Completa todos los campos antes de modificar.",
                "Datos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(idTexto);

        Huesped modiHuesped = new Huesped(id, dni, nombres, apellidos, contacto);

        if (gestionarHuespedes.modificar(modiHuesped) == null) {
            JOptionPane.showMessageDialog(
                this,
                "No se encontró un huésped con ese ID.",
                "Modificar huésped",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Ajusta estos setters según tu clase Huesped
        JOptionPane.showMessageDialog(
            this,
            "Huésped modificado correctamente.",
            "Modificar huésped",
            JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioHuesped();
    }//GEN-LAST:event_btnModificarHuespedActionPerformed

    private void btnAgregarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHuespedActionPerformed
        String dni = txtDniHuesped.getText().trim();
        String nombres = txtNombresHuesped.getText().trim();
        String apellidos = txtApellidosHuesped.getText().trim();
        String contacto = txtContactoHuesped.getText().trim();

        if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Complete al menos DNI, nombres y apellidos.",
                "Registrar huésped",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Huesped h = new Huesped(dni, nombres, apellidos, contacto);

        Huesped registrado = gestionarHuespedes.registrar(h);

        if (registrado != null) {
            JOptionPane.showMessageDialog(
                this,
                "Huésped registrado correctamente.",
                "Registrar huésped",
                JOptionPane.INFORMATION_MESSAGE
            );
            limpiarFormularioHuesped();
        } else {
            JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar el huésped.",
                "Registrar huésped",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAgregarHuespedActionPerformed

    private void btnEliminarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHuespedActionPerformed
        String idTexto = txtIdHuesped.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Ingrese el ID del huésped a eliminar.",
                "Eliminar huésped",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(idTexto);

        ArrayList<Huesped> lista = gestionarHuespedes.getHuespedes();
        Huesped encontrado = null;

        for (Huesped h : lista) {
            if (h.getID() == id) {
                encontrado = h;
                break;
            }
        }

        if (encontrado == null) {
            JOptionPane.showMessageDialog(
                this,
                "No se encontró un huésped con ese ID.",
                "Eliminar huésped",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        gestionarHuespedes.eliminar(encontrado);

        JOptionPane.showMessageDialog(
            this,
            "Huésped eliminado correctamente.",
            "Eliminar huésped",
            JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioHuesped();

    }//GEN-LAST:event_btnEliminarHuespedActionPerformed

    private void btnLimpiarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHuespedActionPerformed
        limpiarFormularioHuesped();
    }//GEN-LAST:event_btnLimpiarHuespedActionPerformed

    private void btnMostrarHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarHuespedesActionPerformed
        ArrayList<Huesped> lista = gestionarHuespedes.getHuespedes();

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No hay huéspedes registrados.",
                "Huéspedes",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Huesped h : lista) {
            mensaje.append(h.toString()).append("\n")
            .append("------------------------\n");
        }

        JOptionPane.showMessageDialog(
            this,
            mensaje.toString(),
            "Huéspedes registrados",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarHuespedesActionPerformed

    private void txtIdHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHuespedActionPerformed
    }//GEN-LAST:event_txtIdHuespedActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JButton btnAgregarHuesped;
    private javax.swing.JButton btnEliminarHuesped;
    private javax.swing.JButton btnLimpiarHuesped;
    private javax.swing.JButton btnModificarHuesped;
    private javax.swing.JButton btnMostrarHuespedes;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblApellidosHuesped;
    private javax.swing.JLabel lblContactoHuesped;
    private javax.swing.JLabel lblDniHuesped;
    private javax.swing.JLabel lblIdHuesped;
    private javax.swing.JLabel lblNombresHuesped;
    private javax.swing.JTextField txtApellidosHuesped;
    private javax.swing.JTextField txtContactoHuesped;
    private javax.swing.JTextField txtDniHuesped;
    private javax.swing.JTextField txtIdHuesped;
    private javax.swing.JTextField txtNombresHuesped;
    // End of variables declaration//GEN-END:variables
}
