/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 20240
 */
import Gestion.GestionarEmpleados;
import Personas.Empleado;


public class InterfazGestionEmpleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGestionEmpleados.class.getName());
    
    
    private GestionarEmpleados gestionarEmpleados;
    /**
     * Creates new form FrmEmpleados
     */
    public InterfazGestionEmpleados() {
        initComponents();
    }
    
    public InterfazGestionEmpleados(GestionarEmpleados gestionarEmpleados) {
    this();
    this.gestionarEmpleados = gestionarEmpleados;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdEmpleado = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblUsuarioEmp = new javax.swing.JLabel();
        lblContrasenaEmp = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtUsuarioEmp = new javax.swing.JTextField();
        txtContrasenaEmp = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        chkAdmin = new javax.swing.JCheckBox();
        panelEmpleados = new javax.swing.JPanel();
        btnModificarEmp = new javax.swing.JButton();
        btnAgregarEmp = new javax.swing.JButton();
        btnEliminarEmp = new javax.swing.JButton();
        btnLimpiarEmp = new javax.swing.JButton();
        btnMostrarEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Empleados");
        setResizable(false);

        lblIdEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdEmpleado.setText("ID (solo para modificar o eliminar):");

        lblDni.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDni.setText("DNI:");

        lblNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNombres.setText("Nombres:");

        lblApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblApellidos.setText("Apellidos");

        lblUsuarioEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUsuarioEmp.setText("Usuario:");

        lblContrasenaEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblContrasenaEmp.setText("Contraseña:");

        txtIdEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdEmpleado.addActionListener(this::txtDniActionPerformed);

        txtDni.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDni.addActionListener(this::txtDniActionPerformed);

        txtApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtUsuarioEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtContrasenaEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRol.setText("Rol (Administrador)");

        chkAdmin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdEmpleado)
                            .addComponent(lblNombres)
                            .addComponent(lblApellidos)
                            .addComponent(lblUsuarioEmp)
                            .addComponent(lblContrasenaEmp)
                            .addComponent(lblDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuarioEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenaEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRol)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkAdmin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdEmpleado)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuarioEmp)
                            .addComponent(txtUsuarioEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContrasenaEmp)
                            .addComponent(txtContrasenaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblRol)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnModificarEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModificarEmp.setText("Modificar");
        btnModificarEmp.addActionListener(this::btnModificarEmpActionPerformed);

        btnAgregarEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarEmp.setText("Agregar");
        btnAgregarEmp.addActionListener(this::btnAgregarEmpActionPerformed);

        btnEliminarEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminarEmp.setText("Eliminar");
        btnEliminarEmp.addActionListener(this::btnEliminarEmpActionPerformed);

        btnLimpiarEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarEmp.setText("Limpiar");
        btnLimpiarEmp.addActionListener(this::btnLimpiarEmpActionPerformed);

        btnMostrarEmp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarEmp.setText("Mostrar Empleados");
        btnMostrarEmp.addActionListener(this::btnMostrarEmpActionPerformed);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(btnAgregarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEmp)
                    .addComponent(btnModificarEmp)
                    .addComponent(btnEliminarEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnLimpiarEmp))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnLimpiarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEmpActionPerformed
        txtIdEmpleado.setText("");
        txtDni.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtUsuarioEmp.setText("");
        txtContrasenaEmp.setText("");
        chkAdmin.setSelected(false);

        txtIdEmpleado.requestFocus();
    }//GEN-LAST:event_btnLimpiarEmpActionPerformed

    private void btnAgregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpActionPerformed

        String dni = txtDni.getText().trim();
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String usuario = txtUsuarioEmp.getText().trim();
        String contrasena = txtContrasenaEmp.getText().trim(); // si luego usas JPasswordField, esto cambia
        boolean esAdmin = chkAdmin.isSelected();

    
        if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || usuario.isEmpty() || contrasena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Completa todos los campos antes de agregar.",
                "Datos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Personas.Empleado nuevo = new Personas.Empleado(
            dni,
            nombres,
            apellidos,
            usuario,
            contrasena,
            esAdmin
        );

        gestionarEmpleados.agregar(nuevo);

    
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Empleado registrado correctamente.",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnAgregarEmpActionPerformed

    private void btnModificarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpActionPerformed
        String idTexto = txtIdEmpleado.getText().trim();
        String dni = txtDni.getText().trim();
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String usuario = txtUsuarioEmp.getText().trim();
        String contrasena = txtContrasenaEmp.getText().trim();
        boolean esAdmin = chkAdmin.isSelected();
        
        if (idTexto.isEmpty() || dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || usuario.isEmpty() || contrasena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Completa todos los campos antes de modificar.",
                "Datos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idEmpleado = Integer.parseInt(idTexto);
        System.out.println(gestionarEmpleados.getEmpleados());

        Empleado encontrado = new Empleado(idEmpleado, dni, nombres, apellidos, usuario, contrasena, esAdmin);

        if (gestionarEmpleados.modificar(encontrado) == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró un empleado con el ID: " + idEmpleado,
                "Empleado no encontrado",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        javax.swing.JOptionPane.showMessageDialog(
        this,
        "Empleado modificado correctamente.",
        "Modificación exitosa",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
        
    }//GEN-LAST:event_btnModificarEmpActionPerformed

    private void btnEliminarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpActionPerformed
        String idTexto = txtIdEmpleado.getText().trim();
        if (idTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingresa el ID del empleado que quieres modificar.",
                "ID requerido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idEmpleado = Integer.parseInt(idTexto);

        Empleado encontrado = null;
        for (Empleado e : gestionarEmpleados.getEmpleados()) {
            if (e.getID() == idEmpleado) {
                encontrado = e;
                break;
            }
        }

        if (encontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró un empleado con el ID: " + idEmpleado,
                "Empleado no encontrado",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }


        int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que deseas eliminar al empleado con ID: " + idEmpleado + "?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            gestionarEmpleados.remover(encontrado);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Empleado eliminado correctamente.",
                "Eliminación exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
  
            btnLimpiarEmpActionPerformed(null);
        }        
    }//GEN-LAST:event_btnEliminarEmpActionPerformed

    private void btnMostrarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpActionPerformed
        if (gestionarEmpleados.getEmpleados().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No hay empleados registrados.",
                    "Lista de empleados",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            StringBuilder sb = new StringBuilder();
            for (Empleado e : gestionarEmpleados.getEmpleados()) {
                sb.append("ID: ").append(e.getID()).append("\n")
                  .append("DNI: ").append(e.getDNI()).append("\n")
                  .append("Nombre: ").append(e.getNombres()).append(" ").append(e.getApellidos()).append("\n")
                  .append("Usuario: ").append(e.getUsuario()).append("\n")
                  .append("Rol: ").append(e.isAdmin() ? "Administrador" : "Recepcionista").append("\n")
                  .append("---------------------------\n");
            }

            javax.swing.JOptionPane.showMessageDialog(
                this,
                sb.toString(),
                "Lista de empleados",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );        
    }//GEN-LAST:event_btnMostrarEmpActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGestionEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmp;
    private javax.swing.JButton btnEliminarEmp;
    private javax.swing.JButton btnLimpiarEmp;
    private javax.swing.JButton btnModificarEmp;
    private javax.swing.JButton btnMostrarEmp;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdEmpleado;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContrasenaEmp;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuarioEmp;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContrasenaEmp;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuarioEmp;
    // End of variables declaration//GEN-END:variables
}
