/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Gestion.GestionarServiciosAdicionales;
import Hotel.ServicioAdicional;
import javax.swing.JOptionPane;
import java.util.ArrayList; 


/**
 *
 * @author 20240
 */

 

public class InterfazGestionServicios extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazGestionServicios
     */
    private GestionarServiciosAdicionales gestionarServiciosAdicionales;
    
    public InterfazGestionServicios(GestionarServiciosAdicionales gestionarServiciosAdicionales) {
        initComponents();
        this.gestionarServiciosAdicionales = gestionarServiciosAdicionales;

        setTitle("Gestión de Servicios Adicionales");
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private void limpiarFormularioServ() {
        txtNombreServ.setText("");
        txtPrecioServ.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelServicios = new javax.swing.JPanel();
        lblIdServ = new javax.swing.JLabel();
        txtIdServ = new javax.swing.JTextField();
        lblNombreServ = new javax.swing.JLabel();
        txtNombreServ = new javax.swing.JTextField();
        lblPrecioServ = new javax.swing.JLabel();
        txtPrecioServ = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarServ = new javax.swing.JButton();
        btnModificarServ = new javax.swing.JButton();
        btnEliminarServ = new javax.swing.JButton();
        btnLimpiarServ = new javax.swing.JButton();
        btnMostrarServ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelServicios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblIdServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdServ.setText("ID (solo para modificar o eliminar):");

        lblNombreServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNombreServ.setText("Nombre:");

        lblPrecioServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPrecioServ.setText("Precio:");

        btnAgregarServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarServ.setText("Agregar");
        btnAgregarServ.addActionListener(this::btnAgregarServActionPerformed);

        btnModificarServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModificarServ.setText("Modificar");
        btnModificarServ.addActionListener(this::btnModificarServActionPerformed);

        btnEliminarServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminarServ.setText("Eliminar");
        btnEliminarServ.addActionListener(this::btnEliminarServActionPerformed);

        btnLimpiarServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarServ.setText("Limpiar");
        btnLimpiarServ.addActionListener(this::btnLimpiarServActionPerformed);

        btnMostrarServ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarServ.setText("Mostrar servicios");
        btnMostrarServ.addActionListener(this::btnMostrarServActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMostrarServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarServ, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btnAgregarServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarServ)
                    .addComponent(btnModificarServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarServ)
                    .addComponent(btnLimpiarServ))
                .addGap(18, 18, 18)
                .addComponent(btnMostrarServ)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdServ)
                    .addComponent(lblNombreServ)
                    .addComponent(lblPrecioServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdServ, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtNombreServ)
                    .addComponent(txtPrecioServ))
                .addContainerGap())
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdServ)
                    .addComponent(txtIdServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreServ)
                    .addComponent(txtNombreServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioServ)
                    .addComponent(txtPrecioServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarServActionPerformed
        String idTexto = txtIdServ.getText().trim();
        String nombre = txtNombreServ.getText().trim();
        String precioTexto = txtPrecioServ.getText().trim();

        if (idTexto.isEmpty() || nombre.isEmpty() || precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Complete todos los campos.",
                    "Modificar servicio",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idServicio = Integer.parseInt(idTexto);
        float precio = Float.parseFloat(precioTexto);

        ServicioAdicional modiServi = new ServicioAdicional(idServicio, nombre, precio);

        if (gestionarServiciosAdicionales.modificar(modiServi) == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un servicio con ese nombre.",
                    "Modificar servicio",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
                this,
                "Servicio modificado correctamente.",
                "Modificar servicio",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioServ();       
    }//GEN-LAST:event_btnModificarServActionPerformed

    private void btnLimpiarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarServActionPerformed
        limpiarFormularioServ(); 
    }//GEN-LAST:event_btnLimpiarServActionPerformed

    private void btnAgregarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServActionPerformed
        String nombre = txtNombreServ.getText().trim();
        String precioTexto = txtPrecioServ.getText().trim();

        if (nombre.isEmpty() || precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Complete nombre y precio.",
                    "Agregar servicio",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        float precio = Float.parseFloat(precioTexto);

        ServicioAdicional serv = new ServicioAdicional(nombre, precio);

        ServicioAdicional agregado = gestionarServiciosAdicionales.agregar(serv);

        if (agregado != null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Servicio agregado correctamente.",
                    "Agregar servicio",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpiarFormularioServ();
        } else {
            // En tu gestor siempre devuelve algo, pero igual dejamos el else por si acaso.
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo agregar el servicio.",
                    "Agregar servicio",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAgregarServActionPerformed

    private void btnMostrarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarServActionPerformed
        ArrayList<ServicioAdicional> lista = gestionarServiciosAdicionales.getServiciosAdicionales();

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay servicios registrados.",
                    "Servicios adicionales",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (ServicioAdicional s : lista) {
            mensaje.append("ID: ").append(s.getID())
                   .append(" | Nombre: ").append(s.getNombre())
                   .append(" | Precio: ").append(s.getPrecio())
                   .append("\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Servicios registrados",
                JOptionPane.INFORMATION_MESSAGE
        );        
    }//GEN-LAST:event_btnMostrarServActionPerformed

    private void btnEliminarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServActionPerformed
        String idTexto = txtIdServ.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el ID del servicio a eliminar.",
                    "Eliminar servicio",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        ArrayList<ServicioAdicional> lista = gestionarServiciosAdicionales.getServiciosAdicionales();
        ServicioAdicional encontrado = null;
        int id = Integer.parseInt(idTexto);

        for (ServicioAdicional s : lista) {
            if (s.getID() == id) {
                encontrado = s;
                break;
            }
        }

        if (encontrado == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un servicio con ese nombre.",
                    "Eliminar servicio",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        gestionarServiciosAdicionales.remover(encontrado);

        JOptionPane.showMessageDialog(
                this,
                "Servicio eliminado correctamente.",
                "Eliminar servicio",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioServ(); 
    }//GEN-LAST:event_btnEliminarServActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServ;
    private javax.swing.JButton btnEliminarServ;
    private javax.swing.JButton btnLimpiarServ;
    private javax.swing.JButton btnModificarServ;
    private javax.swing.JButton btnMostrarServ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdServ;
    private javax.swing.JLabel lblNombreServ;
    private javax.swing.JLabel lblPrecioServ;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JTextField txtIdServ;
    private javax.swing.JTextField txtNombreServ;
    private javax.swing.JTextField txtPrecioServ;
    // End of variables declaration//GEN-END:variables
}
