/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import Gestion.GestionarHabitaciones;
import Hotel.Habitacion;
import javax.swing.JOptionPane;
/**
 *
 * @author 20240
 */
public class InterfazGestionHabitaciones extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazGestionHabitaciones
     */
    private GestionarHabitaciones gestionarHabitaciones;
    

    public InterfazGestionHabitaciones(GestionarHabitaciones gestionarHabitaciones) {
        initComponents();
        

        
        this.gestionarHabitaciones = gestionarHabitaciones;

        setTitle("Gestión de Habitaciones");
        setResizable(false);
        setLocationRelativeTo(null);
        
    
    }
    private void limpiarFormularioHab() {
        txtNumeroHab.setText("");
        txtCapacidadHab.setText("");
        txtPrecioHab.setText("");
        cboTipoHab.setSelectedIndex(0);
        cboEstadoHab.setSelectedIndex(0);
        chkDisponible.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHabitaciones = new javax.swing.JPanel();
        lblCapacidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNumeroHab = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblDisponible = new javax.swing.JLabel();
        txtNumeroHab = new javax.swing.JTextField();
        txtCapacidadHab = new javax.swing.JTextField();
        txtPrecioHab = new javax.swing.JTextField();
        cboTipoHab = new javax.swing.JComboBox<>();
        cboEstadoHab = new javax.swing.JComboBox<>();
        chkDisponible = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarHab = new javax.swing.JButton();
        btnModificarHab = new javax.swing.JButton();
        btnLimpiarHab = new javax.swing.JButton();
        btnEliminarHab = new javax.swing.JButton();
        btnMostrarHab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCapacidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCapacidad.setText("Capacidad máxima:");

        lblPrecio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPrecio.setText("Precio por noche:");

        lblTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");

        lblNumeroHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNumeroHab.setText("Número:");

        lblEstado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");

        lblDisponible.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDisponible.setText("Disponible:");

        txtNumeroHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtCapacidadHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtPrecioHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cboTipoHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboTipoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Suite" }));
        cboTipoHab.addActionListener(this::cboTipoHabActionPerformed);

        cboEstadoHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboEstadoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpia", "Sucia", "En limpieza" }));
        cboEstadoHab.addActionListener(this::cboEstadoHabActionPerformed);

        btnAgregarHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarHab.setText("Agregar");
        btnAgregarHab.addActionListener(this::btnAgregarHabActionPerformed);

        btnModificarHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModificarHab.setText("Modificar");
        btnModificarHab.addActionListener(this::btnModificarHabActionPerformed);

        btnLimpiarHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarHab.setText("Limpiar");
        btnLimpiarHab.addActionListener(this::btnLimpiarHabActionPerformed);

        btnEliminarHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminarHab.setText("Eliminar");
        btnEliminarHab.addActionListener(this::btnEliminarHabActionPerformed);

        btnMostrarHab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarHab.setText("Mostrar habitaciones");
        btnMostrarHab.addActionListener(this::btnMostrarHabActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarHab, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarHab)
                    .addComponent(btnModificarHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarHab)
                    .addComponent(btnEliminarHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnMostrarHab)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHabitacionesLayout = new javax.swing.GroupLayout(panelHabitaciones);
        panelHabitaciones.setLayout(panelHabitacionesLayout);
        panelHabitacionesLayout.setHorizontalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroHab, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumeroHab, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtCapacidadHab)
                                .addComponent(txtPrecioHab))
                            .addComponent(cboTipoHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEstadoHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addComponent(lblDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDisponible)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHabitacionesLayout.setVerticalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroHab)
                    .addComponent(txtNumeroHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidad)
                    .addComponent(txtCapacidadHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecioHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cboTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cboEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponible)
                    .addComponent(chkDisponible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoHabActionPerformed
    }//GEN-LAST:event_cboTipoHabActionPerformed

    private void cboEstadoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoHabActionPerformed
    }//GEN-LAST:event_cboEstadoHabActionPerformed

    private void btnLimpiarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHabActionPerformed
        limpiarFormularioHab();
    }//GEN-LAST:event_btnLimpiarHabActionPerformed

    private void btnAgregarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHabActionPerformed
        int numero = Integer.parseInt(txtNumeroHab.getText().trim());
        int capacidad = Integer.parseInt(txtCapacidadHab.getText().trim());
        float precio = Float.parseFloat(txtPrecioHab.getText().trim());

        String tipo = cboTipoHab.getSelectedItem().toString();
        String estado = cboEstadoHab.getSelectedItem().toString();

        Habitacion hab = new Habitacion(numero, capacidad, precio, tipo, estado);

        hab.setDisponible(chkDisponible.isSelected());

        Habitacion agregada = gestionarHabitaciones.agregar(hab);

        if (agregada != null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Habitación agregada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpiarFormularioHab();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe una habitación con ese número.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAgregarHabActionPerformed

    private void btnMostrarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarHabActionPerformed

        java.util.ArrayList<Habitacion> lista = gestionarHabitaciones.getHabitaciones();

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay habitaciones registradas.",
                    "Habitaciones",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Habitacion h : lista) {
            mensaje.append("Número: ").append(h.getNumero())
                   .append(" | Tipo: ").append(h.getTipoHabitacion())
                   .append(" | Capacidad: ").append(h.getCapacidadMAX())
                   .append(" | Precio: ").append(h.getPrecioPorNoche())
                   .append(" | Estado: ").append(h.getEstadoHabitacion())
                   .append(" | Disponible: ").append(h.isDisponible())
                   .append("\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Habitaciones registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarHabActionPerformed

    private void btnEliminarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabActionPerformed
        if (txtNumeroHab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el número de la habitación a eliminar.",
                    "Eliminar",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int numero = Integer.parseInt(txtNumeroHab.getText().trim());

        Habitacion encontrada = null;
        for (Habitacion h : gestionarHabitaciones.getHabitaciones()) {
            if (h.getNumero() == numero) {
                encontrada = h;
                break;
            }
        }

        if (encontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una habitación con ese número.",
                    "Eliminar",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }


        gestionarHabitaciones.remover(encontrada);

        JOptionPane.showMessageDialog(
                this,
                "Habitación eliminada correctamente.",
                "Eliminar",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioHab();
    }//GEN-LAST:event_btnEliminarHabActionPerformed

    private void btnModificarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHabActionPerformed

        int numero = Integer.parseInt(txtNumeroHab.getText());

        java.util.ArrayList<Habitacion> lista = gestionarHabitaciones.getHabitaciones();
        Habitacion encontrada = null;

        for (Habitacion h : lista) {
            if (h.getNumero() == numero) {
                encontrada = h;
                break;
            }
        }

        if (encontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una habitación con ese número.",
                    "Modificar habitación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int capacidad = Integer.parseInt(txtCapacidadHab.getText());
        float precio = Float.parseFloat(txtPrecioHab.getText());
        String tipo = cboTipoHab.getSelectedItem().toString();
        String estado = cboEstadoHab.getSelectedItem().toString();
        boolean disponible = chkDisponible.isSelected();

        encontrada.setCapacidadMAX(capacidad);
        encontrada.setPrecioPorNoche(precio);
        encontrada.setTipoHabitacion(tipo);
        encontrada.setEstadoHabitacion(estado);
        encontrada.setDisponible(disponible);


        JOptionPane.showMessageDialog(
                this,
                "Habitación modificada correctamente.",
                "Modificar habitación",
                JOptionPane.INFORMATION_MESSAGE
        );


        limpiarFormularioHab();
    }//GEN-LAST:event_btnModificarHabActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarHab;
    private javax.swing.JButton btnEliminarHab;
    private javax.swing.JButton btnLimpiarHab;
    private javax.swing.JButton btnModificarHab;
    private javax.swing.JButton btnMostrarHab;
    private javax.swing.JComboBox<String> cboEstadoHab;
    private javax.swing.JComboBox<String> cboTipoHab;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumeroHab;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panelHabitaciones;
    private javax.swing.JTextField txtCapacidadHab;
    private javax.swing.JTextField txtNumeroHab;
    private javax.swing.JTextField txtPrecioHab;
    // End of variables declaration//GEN-END:variables
}
