/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Gestion.GestionarEstadias;
import Reportes.ReporteIngresos;
import RecursosBase.Fecha;
import javax.swing.JOptionPane;

/**
 *
 * @author 20240
 */
public class InterfazReporteIngresos extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazReporteIngresos
     */
    private GestionarEstadias gestionarEstadias;
    
    public InterfazReporteIngresos(GestionarEstadias gestionarEstadias) {
        initComponents();
        this.gestionarEstadias = gestionarEstadias;

        setTitle("Reporte de ingresos");
        setResizable(false);
        setLocationRelativeTo(null);
    }
    public InterfazReporteIngresos() {
        initComponents();
        this.gestionarEstadias = new GestionarEstadias(); // vacío para pruebas

        setTitle("Reporte de ingresos");
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private void limpiarCampos() {
        txtDiaInicio.setText("");
        txtMesInicio.setText("");
        txtAnioInicio.setText("");
        txtDiaFinal.setText("");
        txtMesFinal.setText("");
        txtAnioFinal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFechas = new javax.swing.JPanel();
        lblFechaInicio = new javax.swing.JLabel();
        txtDiaInicio = new javax.swing.JTextField();
        txtMesInicio = new javax.swing.JTextField();
        txtAnioInicio = new javax.swing.JTextField();
        lblFormato1 = new javax.swing.JLabel();
        lblFormato2 = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();
        txtDiaFinal = new javax.swing.JTextField();
        lblFormato3 = new javax.swing.JLabel();
        lblFormato4 = new javax.swing.JLabel();
        txtMesFinal = new javax.swing.JTextField();
        txtAnioFinal = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFechaInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFechaInicio.setText("Fecha inicio (dd / mm / aaaa):");

        txtDiaInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMesInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAnioInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblFormato1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFormato1.setText("/");

        lblFormato2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFormato2.setText("/");

        lblFechaFinal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFechaFinal.setText("Fecha final (dd / mm / aaaa):");

        txtDiaFinal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblFormato3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFormato3.setText("/");

        lblFormato4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFormato4.setText("/");

        txtMesFinal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAnioFinal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnGenerar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGenerar.setText("Generar reporte");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCerrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(18, 18, 18))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFechasLayout = new javax.swing.GroupLayout(panelFechas);
        panelFechas.setLayout(panelFechasLayout);
        panelFechasLayout.setHorizontalGroup(
            panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFechasLayout.createSequentialGroup()
                        .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblFechaFinal))
                        .addGap(18, 18, 18)
                        .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelFechasLayout.createSequentialGroup()
                                .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFormato1))
                            .addGroup(panelFechasLayout.createSequentialGroup()
                                .addComponent(txtDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFormato3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFormato4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFormato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFechasLayout.setVerticalGroup(
            panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormato1)
                    .addComponent(lblFormato2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaFinal)
                    .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFormato3)
                        .addComponent(lblFormato4)
                        .addComponent(txtMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAnioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos(); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String dI = txtDiaInicio.getText().trim();
        String mI = txtMesInicio.getText().trim();
        String aI = txtAnioInicio.getText().trim();
        String dF = txtDiaFinal.getText().trim();
        String mF = txtMesFinal.getText().trim();
        String aF = txtAnioFinal.getText().trim();

        if (dI.isEmpty() || mI.isEmpty() || aI.isEmpty()
                || dF.isEmpty() || mF.isEmpty() || aF.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Complete todas las fechas.",
                    "Reporte de ingresos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            int diaI = Integer.parseInt(dI);
            int mesI = Integer.parseInt(mI);
            int anioI = Integer.parseInt(aI);

            int diaF = Integer.parseInt(dF);
            int mesF = Integer.parseInt(mF);
            int anioF = Integer.parseInt(aF);

            Fecha fechaInicio = new Fecha(diaI, mesI, anioI);
            Fecha fechaFinal  = new Fecha(diaF, mesF, anioF);

            // chequeo opcional: inicio no después de final
            if (RecursosBase.Fecha.esDespues(fechaInicio, fechaFinal)) {
                JOptionPane.showMessageDialog(
                        this,
                        "La fecha de inicio no puede ser posterior a la fecha final.",
                        "Reporte de ingresos",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            ReporteIngresos reporte =
                    new ReporteIngresos(gestionarEstadias, fechaInicio, fechaFinal);

            JOptionPane.showMessageDialog(
                    this,
                    reporte.detallarIngresos(),
                    "Reporte de ingresos",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Las fechas deben contener solo números.",
                    "Error en fechas",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFormato1;
    private javax.swing.JLabel lblFormato2;
    private javax.swing.JLabel lblFormato3;
    private javax.swing.JLabel lblFormato4;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFechas;
    private javax.swing.JTextField txtAnioFinal;
    private javax.swing.JTextField txtAnioInicio;
    private javax.swing.JTextField txtDiaFinal;
    private javax.swing.JTextField txtDiaInicio;
    private javax.swing.JTextField txtMesFinal;
    private javax.swing.JTextField txtMesInicio;
    // End of variables declaration//GEN-END:variables
}
