/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 20240
 */
import Gestion.GestionarReservaciones;
import Gestion.GestionarHuespedes;
import Servicios.Reservacion;
import Personas.Huesped;
import RecursosBase.Fecha;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class InterfazGestionReservaciones extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazGestionReservaciones
     */
        private GestionarReservaciones gestionarReservaciones;
        private GestionarHuespedes gestionarHuespedes;

        public InterfazGestionReservaciones(GestionarReservaciones gestionarReservaciones,
                                            GestionarHuespedes gestionarHuespedes) {
            initComponents();
            this.gestionarReservaciones = gestionarReservaciones;
            this.gestionarHuespedes = gestionarHuespedes;

            setTitle("Gestión de Reservaciones");
            setResizable(false);
            setLocationRelativeTo(null);

        
        }
        
        private void limpiarFormularioReserva() {
            txtIdReserva.setText("");
            txtDniHuesped.setText("");
            txtDiaInicio.setText("");
            txtMesInicio.setText("");
            txtAnioInicio.setText("");
            txtDiaFin.setText("");
            txtMesFin.setText("");
            txtAnioFin.setText("");
            cboTipoHabitacionReserva.setSelectedIndex(0);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdReserva = new javax.swing.JLabel();
        lblDniHuesped = new javax.swing.JLabel();
        lblDiaInicio = new javax.swing.JLabel();
        lblMesInicio = new javax.swing.JLabel();
        lblAnioInicio = new javax.swing.JLabel();
        lblDiaFin = new javax.swing.JLabel();
        lblFechasInicio = new javax.swing.JLabel();
        lblFechasFin = new javax.swing.JLabel();
        lblMesFin = new javax.swing.JLabel();
        lblAnioFin = new javax.swing.JLabel();
        cboTipoHabitacionReserva = new javax.swing.JComboBox<>();
        lblTipoHabitación = new javax.swing.JLabel();
        txtIdReserva = new javax.swing.JTextField();
        txtDniHuesped = new javax.swing.JTextField();
        txtDiaInicio = new javax.swing.JTextField();
        txtMesInicio = new javax.swing.JTextField();
        txtAnioInicio = new javax.swing.JTextField();
        txtDiaFin = new javax.swing.JTextField();
        txtMesFin = new javax.swing.JTextField();
        txtAnioFin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarReserva = new javax.swing.JButton();
        btnModificarReserva = new javax.swing.JButton();
        btnEliminarReserva = new javax.swing.JButton();
        btnMostrarHuespedes = new javax.swing.JButton();
        btnMostrarReservas = new javax.swing.JButton();
        btnLimpiarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIdReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdReserva.setText("ID (solo para modificar o eliminar):");

        lblDniHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDniHuesped.setText("DNI:");

        lblDiaInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDiaInicio.setText("Día:");

        lblMesInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMesInicio.setText("Mes:");

        lblAnioInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAnioInicio.setText("Año:");

        lblDiaFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDiaFin.setText("Día:");

        lblFechasInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFechasInicio.setText("--Fechas de inicio--");

        lblFechasFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFechasFin.setText("--Fechas de fin--");

        lblMesFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMesFin.setText("Mes:");

        lblAnioFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAnioFin.setText("Año:");

        cboTipoHabitacionReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboTipoHabitacionReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Suite" }));

        lblTipoHabitación.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTipoHabitación.setText("Tipo de habitación");

        txtIdReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdReserva.addActionListener(this::txtIdReservaActionPerformed);

        txtDniHuesped.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDiaInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMesInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAnioInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDiaFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMesFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAnioFin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnAgregarReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarReserva.setText("Agregar ");
        btnAgregarReserva.addActionListener(this::btnAgregarReservaActionPerformed);

        btnModificarReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModificarReserva.setText("Modificar");
        btnModificarReserva.addActionListener(this::btnModificarReservaActionPerformed);

        btnEliminarReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminarReserva.setText("Eliminar");
        btnEliminarReserva.addActionListener(this::btnEliminarReservaActionPerformed);

        btnMostrarHuespedes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarHuespedes.setText("Mostrar huéspedes");
        btnMostrarHuespedes.addActionListener(this::btnMostrarHuespedesActionPerformed);

        btnMostrarReservas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarReservas.setText("Mostrar reservas");
        btnMostrarReservas.addActionListener(this::btnMostrarReservasActionPerformed);

        btnLimpiarReserva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarReserva.setText("Limpiar");
        btnLimpiarReserva.addActionListener(this::btnLimpiarReservaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarReserva)
                    .addComponent(btnModificarReserva))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarReserva)
                    .addComponent(btnLimpiarReserva))
                .addGap(18, 18, 18)
                .addComponent(btnMostrarHuespedes)
                .addComponent(btnMostrarReservas)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipoHabitación)
                        .addGap(18, 18, 18)
                        .addComponent(cboTipoHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdReserva)
                            .addComponent(lblDniHuesped))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(txtDniHuesped))
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblFechasInicio)
                                .addGap(65, 65, 65)
                                .addComponent(lblFechasFin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiaInicio)
                                    .addComponent(lblAnioInicio)
                                    .addComponent(lblMesInicio))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(txtMesInicio)
                                    .addComponent(txtAnioInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMesFin)
                                    .addComponent(lblDiaFin)
                                    .addComponent(lblAnioFin))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(txtMesFin)
                                    .addComponent(txtAnioFin))))
                        .addGap(74, 74, 74))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdReserva)
                    .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniHuesped)
                    .addComponent(txtDniHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechasInicio)
                    .addComponent(lblFechasFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaInicio)
                    .addComponent(lblDiaFin)
                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAnioInicio)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMesInicio))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMesFin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAnioFin)))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoHabitación))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarReservaActionPerformed
        limpiarFormularioReserva();
    }//GEN-LAST:event_btnLimpiarReservaActionPerformed

    private void btnEliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReservaActionPerformed
        String idTexto = txtIdReserva.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el ID de la reservación a eliminar.",
                    "Eliminar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(idTexto);

        ArrayList<Reservacion> lista = gestionarReservaciones.getReservaciones();
        Reservacion encontrada = null;

        for (Reservacion r : lista) {
            if (r.getID() == id) {
                encontrada = r;
                break;
            }
        }

        if (encontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró una reservación con ese ID.",
                    "Eliminar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        gestionarReservaciones.eliminar(encontrada);

        JOptionPane.showMessageDialog(
                this,
                "Reservación eliminada correctamente.",
                "Eliminar reservación",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioReserva();
    }//GEN-LAST:event_btnEliminarReservaActionPerformed

    private void btnAgregarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReservaActionPerformed
        String dni = txtDniHuesped.getText().trim();
        String diaIniTexto = txtDiaInicio.getText().trim();
        String mesIniTexto = txtMesInicio.getText().trim();
        String anioIniTexto = txtAnioInicio.getText().trim();
        String diaFinTexto = txtDiaFin.getText().trim();
        String mesFinTexto = txtMesFin.getText().trim();
        String anioFinTexto = txtAnioFin.getText().trim();
        String tipo = cboTipoHabitacionReserva.getSelectedItem().toString();

        if (dni.isEmpty() || diaIniTexto.isEmpty() || mesIniTexto.isEmpty() ||
            anioIniTexto.isEmpty() || diaFinTexto.isEmpty() || mesFinTexto.isEmpty() ||
            anioFinTexto.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Complete DNI y todas las fechas.",
                    "Registrar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int diaIni = Integer.parseInt(diaIniTexto);
        int mesIni = Integer.parseInt(mesIniTexto);
        int anioIni = Integer.parseInt(anioIniTexto);
        int diaFin = Integer.parseInt(diaFinTexto);
        int mesFin = Integer.parseInt(mesFinTexto);
        int anioFin = Integer.parseInt(anioFinTexto);

        Fecha inicio = new Fecha(diaIni, mesIni, anioIni);
        Fecha fin = new Fecha(diaFin, mesFin, anioFin);

        // Verificamos que inicio sea antes que fin
        if (!Fecha.esAntes(inicio, fin)) {
            JOptionPane.showMessageDialog(
                    this,
                    "La fecha de inicio debe ser antes que la fecha final.",
                    "Registrar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Buscar huésped por DNI
        ArrayList<Huesped> listaH = gestionarHuespedes.getHuespedes();
        Huesped responsable = null;

        for (Huesped h : listaH) {
            if (h.getDNI().equals(dni)) {
                responsable = h;
                break;
            }
        }

        if (responsable == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe un huésped con ese DNI. Regístrelo primero.",
                    "Registrar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Reservacion r = new Reservacion(inicio, fin, tipo, responsable);

        Reservacion registrada = gestionarReservaciones.registrar(r);

        if (registrada != null) {
            txtIdReserva.setText(String.valueOf(registrada.getID()));

            JOptionPane.showMessageDialog(
                    this,
                    "Reservación registrada correctamente.\nID: " + registrada.getID(),
                    "Registrar reservación",
                    JOptionPane.INFORMATION_MESSAGE
            );

            limpiarFormularioReserva();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar la reservación (no hay habitaciones disponibles).",
                    "Registrar reservación",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAgregarReservaActionPerformed

    private void btnMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservasActionPerformed
        ArrayList<Reservacion> lista = gestionarReservaciones.getReservaciones();

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay reservaciones registradas.",
                    "Reservaciones",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Reservacion r : lista) {
            mensaje.append("ID: ").append(r.getID()).append("\n")
                   .append("Fecha inicio: ").append(r.getFechaInicio()).append("\n")
                   .append("Fecha final: ").append(r.getFechaFinal()).append("\n")
                   .append("Duración: ").append(r.getDuracion()).append(" noches\n")
                   .append("Tipo habitación: ").append(r.getTipoHabitacion()).append("\n")
                   .append("Huésped responsable: ").append(r.getHuespedResponsable().getNombres())
                   .append(" ").append(r.getHuespedResponsable().getApellidos())
                   .append(" (DNI: ").append(r.getHuespedResponsable().getDNI()).append(")\n")
                   .append("--------------------------\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Reservaciones registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarReservasActionPerformed

    private void btnMostrarHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservasActionPerformed
        ArrayList<Huesped> lista = gestionarHuespedes.getHuespedes();

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay huéspedes registrados.",
                    "Huéspedes",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Huesped r : lista) {
            mensaje.append("DNI: ").append(r.getDNI()).append("\n")
                   .append("Nombres: ").append(r.getNombres()).append("\n")
                   .append("Apellidos: ").append(r.getApellidos()).append("\n")
                   .append("--------------------------\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Huéspedes registrados",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarReservasActionPerformed

    private void btnModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarReservaActionPerformed
        String idTexto = txtIdReserva.getText().trim();
        String dni = txtDniHuesped.getText().trim();
        String diaIniTexto = txtDiaInicio.getText().trim();
        String mesIniTexto = txtMesInicio.getText().trim();
        String anioIniTexto = txtAnioInicio.getText().trim();
        String diaFinTexto = txtDiaFin.getText().trim();
        String mesFinTexto = txtMesFin.getText().trim();
        String anioFinTexto = txtAnioFin.getText().trim();
        String tipo = cboTipoHabitacionReserva.getSelectedItem().toString();

        if (idTexto.isEmpty() || dni.isEmpty() || diaIniTexto.isEmpty() || mesIniTexto.isEmpty() ||
            anioIniTexto.isEmpty() || diaFinTexto.isEmpty() || mesFinTexto.isEmpty() ||
            anioFinTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Completa todos los campos antes de modificar.",
                "Datos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int diaIni = Integer.parseInt(diaIniTexto);
        int mesIni = Integer.parseInt(mesIniTexto);
        int anioIni = Integer.parseInt(anioIniTexto);
        int diaFin = Integer.parseInt(diaFinTexto);
        int mesFin = Integer.parseInt(mesFinTexto);
        int anioFin = Integer.parseInt(anioFinTexto);

        Fecha inicio = new Fecha(diaIni, mesIni, anioIni);
        Fecha fin = new Fecha(diaFin, mesFin, anioFin);

        if (!Fecha.esDespues(fin, inicio)) {
            JOptionPane.showMessageDialog(
                    this,
                    "La fecha de inicio debe ser antes que la fecha final.",
                    "Modificar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Buscar huésped por DNI
        ArrayList<Huesped> listaH = gestionarHuespedes.getHuespedes();
        Huesped responsable = null;

        for (Huesped h : listaH) {
            if (h.getDNI().equals(dni)) {
                responsable = h;
                break;
            }
        }

        if (responsable == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe un huésped con ese DNI.",
                    "Modificar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Reservacion modReservacion = new Reservacion(inicio, fin, tipo, responsable);

        if (gestionarReservaciones.modificar(modReservacion) == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró una reservación con ese ID.",
                    "Modificar reservación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
                this,
                "Reservación modificada correctamente.",
                "Modificar reservación",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioReserva();
    }//GEN-LAST:event_btnModificarReservaActionPerformed

    private void txtIdReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdReservaActionPerformed
    }//GEN-LAST:event_txtIdReservaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarReserva;
    private javax.swing.JButton btnEliminarReserva;
    private javax.swing.JButton btnLimpiarReserva;
    private javax.swing.JButton btnModificarReserva;
    private javax.swing.JButton btnMostrarReservas;
    private javax.swing.JButton btnMostrarHuespedes;
    private javax.swing.JComboBox<String> cboTipoHabitacionReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnioFin;
    private javax.swing.JLabel lblAnioInicio;
    private javax.swing.JLabel lblDiaFin;
    private javax.swing.JLabel lblDiaInicio;
    private javax.swing.JLabel lblDniHuesped;
    private javax.swing.JLabel lblFechasFin;
    private javax.swing.JLabel lblFechasInicio;
    private javax.swing.JLabel lblIdReserva;
    private javax.swing.JLabel lblMesFin;
    private javax.swing.JLabel lblMesInicio;
    private javax.swing.JLabel lblTipoHabitación;
    private javax.swing.JTextField txtAnioFin;
    private javax.swing.JTextField txtAnioInicio;
    private javax.swing.JTextField txtDiaFin;
    private javax.swing.JTextField txtDiaInicio;
    private javax.swing.JTextField txtDniHuesped;
    private javax.swing.JTextField txtIdReserva;
    private javax.swing.JTextField txtMesFin;
    private javax.swing.JTextField txtMesInicio;
    // End of variables declaration//GEN-END:variables
}
