/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 20240
 */
import Gestion.GestionarEstadias;
import Gestion.GestionarReservaciones;
import Gestion.GestionarHabitaciones;
import Gestion.GestionarServiciosAdicionales;
import Servicios.Estadia;
import Servicios.Reservacion;
import Hotel.Habitacion;
import Hotel.ServicioAdicional;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class InterfazGestionEstadias extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazGestionEstadias
     */
    private GestionarEstadias gestionarEstadias;
    private GestionarReservaciones gestionarReservaciones;
    private GestionarHabitaciones gestionarHabitaciones;
    private GestionarServiciosAdicionales gestionarServiciosAdicionales;
    
    public InterfazGestionEstadias(GestionarEstadias gestionarEstadias,
                                   GestionarReservaciones gestionarReservaciones,
                                   GestionarHabitaciones gestionarHabitaciones,
                                   GestionarServiciosAdicionales gestionarServiciosAdicionales) {
        initComponents();
        this.gestionarEstadias = gestionarEstadias;
        this.gestionarReservaciones = gestionarReservaciones;
        this.gestionarHabitaciones = gestionarHabitaciones;
        this.gestionarServiciosAdicionales = gestionarServiciosAdicionales;

        setTitle("Gestión de Estadías");
        setResizable(false);
        setLocationRelativeTo(null);

    }
    
    private void limpiarFormularioEstadia() {
        txtIdEstadia.setText("");
        txtIdReservacion.setText("");
        txtNumeroHabitacion.setText("");
        txtIdServicio.setText("");
        cboEstadoHabitacion.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstadias = new javax.swing.JPanel();
        lblIdEstadia = new javax.swing.JLabel();
        txtIdEstadia = new javax.swing.JTextField();
        lblIdReservacion = new javax.swing.JLabel();
        txtIdReservacion = new javax.swing.JTextField();
        lblNumeroHabitacion = new javax.swing.JLabel();
        txtNumeroHabitacion = new javax.swing.JTextField();
        lblEstadoHabitacion = new javax.swing.JLabel();
        cboEstadoHabitacion = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnRegistrarConsumo = new javax.swing.JButton();
        btnMostrarEstadias = new javax.swing.JButton();
        btnMostrarHabitaciones = new javax.swing.JButton();
        btnMostrarReservas = new javax.swing.JButton();
        btnMostrarServicios = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblIdServicio = new javax.swing.JLabel();
        txtIdServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIdEstadia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdEstadia.setText("ID Estadía (solo para checkOut):");

        txtIdEstadia.addActionListener(this::txtIdEstadiaActionPerformed);

        lblIdReservacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdReservacion.setText("ID Reservación:");

        txtIdReservacion.addActionListener(this::txtIdReservacionActionPerformed);

        lblNumeroHabitacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNumeroHabitacion.setText("N° Habitación:");

        txtNumeroHabitacion.addActionListener(this::txtNumeroHabitacionActionPerformed);

        lblEstadoHabitacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEstadoHabitacion.setText("Estado habitación (checkout):");

        cboEstadoHabitacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboEstadoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucia", "En limpieza" }));

        btnCheckIn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCheckIn.setText("Check-in");
        btnCheckIn.addActionListener(this::btnCheckInActionPerformed);

        btnCheckOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCheckOut.setText("Check-out");
        btnCheckOut.addActionListener(this::btnCheckOutActionPerformed);

        btnRegistrarConsumo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarConsumo.setText("Registrar consumo");
        btnRegistrarConsumo.addActionListener(this::btnRegistrarConsumoActionPerformed);

        btnMostrarReservas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarReservas.setText("Mostrar reservaciones");
        btnMostrarReservas.addActionListener(this::btnMostrarReservasActionPerformed);

        btnMostrarServicios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarServicios.setText("Mostrar servicios adicionales");
        btnMostrarServicios.addActionListener(this::btnMostrarServiciosActionPerformed);

        btnMostrarEstadias.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarEstadias.setText("Mostrar estadías");
        btnMostrarEstadias.addActionListener(this::btnMostrarEstadiasActionPerformed);

        btnMostrarHabitaciones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarHabitaciones.setText("Mostrar habitaciones");
        btnMostrarHabitaciones.addActionListener(this::btnMostrarHabitacionesActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCheckOut))
                            .addComponent(btnMostrarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarEstadias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckIn)
                    .addComponent(btnCheckOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarEstadias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarServicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIdServicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIdServicio.setText("ID Servicio adicional:");

        txtIdServicio.addActionListener(this::txtIdServicioActionPerformed);

        javax.swing.GroupLayout panelEstadiasLayout = new javax.swing.GroupLayout(panelEstadias);
        panelEstadias.setLayout(panelEstadiasLayout);
        panelEstadiasLayout.setHorizontalGroup(
            panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadiasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEstadiasLayout.createSequentialGroup()
                        .addComponent(lblIdServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEstadiasLayout.createSequentialGroup()
                        .addComponent(lblNumeroHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEstadiasLayout.createSequentialGroup()
                        .addComponent(lblIdEstadia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadiasLayout.createSequentialGroup()
                        .addComponent(lblIdReservacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadiasLayout.createSequentialGroup()
                        .addComponent(lblEstadoHabitacion)
                        .addGap(29, 29, 29)
                        .addComponent(cboEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(panelEstadiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEstadiasLayout.setVerticalGroup(
            panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadiasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdReservacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroHabitacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstadiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoHabitacion)
                    .addComponent(cboEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstadias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstadias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEstadiaActionPerformed
    }//GEN-LAST:event_txtIdEstadiaActionPerformed

    private void txtIdReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdReservacionActionPerformed
    }//GEN-LAST:event_txtIdReservacionActionPerformed

    private void txtNumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionActionPerformed
    }//GEN-LAST:event_txtNumeroHabitacionActionPerformed

    private void txtIdServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdServicioActionPerformed
    }//GEN-LAST:event_txtIdServicioActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        String idResTexto = txtIdReservacion.getText().trim();
        String numHabTexto = txtNumeroHabitacion.getText().trim();

        if (idResTexto.isEmpty() || numHabTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese ID de reservación y número de habitación.",
                    "Check-in",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idRes;
        int numHab;
        try {
            idRes = Integer.parseInt(idResTexto);
            numHab = Integer.parseInt(numHabTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "El ID de reservación y el número de habitación deben ser numéricos.",
                    "Check-in",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

       
        Reservacion reservaEncontrada = null;
        for (Reservacion r : gestionarReservaciones.getReservaciones()) {
            if (r.getID() == idRes) {
                reservaEncontrada = r;
                break;
            }
        }

        if (reservaEncontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una reservación con ese ID.",
                    "Check-in",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Habitacion habEncontrada = null;
        for (Habitacion h : gestionarHabitaciones.getHabitaciones()) {
            if (h.getNumero() == numHab) {
                habEncontrada = h;
                break;
            }
        }

        if (habEncontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una habitación con ese número.",
                    "Check-in",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Estadia est = new Estadia(reservaEncontrada, habEncontrada);
        est.setCostoHabitacion(habEncontrada.getPrecioPorNoche());

        Estadia registrada = gestionarEstadias.checkIn(
                est,
                gestionarReservaciones.getReservaciones(),
                gestionarHabitaciones.getHabitaciones()
        );

        if (registrada != null) {
            gestionarHabitaciones.modificar(registrada.getHabitacion());

            txtIdEstadia.setText(String.valueOf(registrada.getId()));
            JOptionPane.showMessageDialog(
                    this,
                    "Check-in registrado. ID de estadía: " + registrada.getId(),
                    "Check-in",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "La habitación no está disponible o la reservación no es válida.",
                    "Check-in",
                    JOptionPane.ERROR_MESSAGE
            );
        }      
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        String idTexto = txtIdEstadia.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el ID de la estadía para hacer el check-out.",
                    "Check-out",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id;
        try {
            id = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "El ID de la estadía debe ser numérico.",
                    "Check-out",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Estadia encontrada = null;
        for (Estadia e : gestionarEstadias.getEstadiasCheckIn()) {
            if (e.getId() == id) {
                encontrada = e;
                break;
            }
        }
        if (encontrada == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una estadía activa con ese ID.",
                    "Check-out",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String nuevoEstado = cboEstadoHabitacion.getSelectedItem().toString();

        Estadia finalizada = gestionarEstadias.checkOut(encontrada, nuevoEstado);

        if (finalizada != null) {
            gestionarHabitaciones.modificar(finalizada.getHabitacion());

            JOptionPane.showMessageDialog(
                    this,
                    "Check-out registrado.\n"
                    + "Costo habitación: " + finalizada.getCostoHabitacion() + "\n"
                    + "Costo servicios: " + finalizada.getCostoServicios() + "\n"
                    + "Costo total: " + finalizada.getCostoTotal(),
                    "Check-out",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpiarFormularioEstadia();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el check-out.",
                    "Check-out",
                    JOptionPane.ERROR_MESSAGE
            );
        }        
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnRegistrarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConsumoActionPerformed
        String idEstTexto = txtIdEstadia.getText().trim();
        String idServTexto = txtIdServicio.getText().trim();

        if (idEstTexto.isEmpty() || idServTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese ID de estadía e ID de servicio adicional.",
                    "Registrar consumo",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idEst = Integer.parseInt(idEstTexto);
        int idServ = Integer.parseInt(idServTexto);

        // Buscar estadía activa
        Estadia est = null;
        for (Estadia e : gestionarEstadias.getEstadiasCheckIn()) {
            if (e.getId() == idEst) {
                est = e;
                break;
            }
        }

        if (est == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe una estadía activa con ese ID.",
                    "Registrar consumo",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Buscar servicio adicional
        ServicioAdicional serv = null;
        for (ServicioAdicional s : gestionarServiciosAdicionales.getServiciosAdicionales()) {
            if (s.getID() == idServ) {
                serv = s;
                break;
            }
        }

        if (serv == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No existe un servicio adicional con ese ID.",
                    "Registrar consumo",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (gestionarEstadias.registrarConsumoServicioAdicional(est, gestionarServiciosAdicionales, serv) == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Consumo registrado correctamente.",
                    "Registrar consumo",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el consumo.",
                    "Registrar consumo",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnRegistrarConsumoActionPerformed

    private void btnMostrarEstadiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEstadiasActionPerformed
        ArrayList<Estadia> activas = gestionarEstadias.getEstadiasCheckIn();
        ArrayList<Estadia> finalizadas = gestionarEstadias.getEstadiasCheckOut();

        if ((activas == null || activas.isEmpty()) &&
            (finalizadas == null || finalizadas.isEmpty())) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay estadías registradas.",
                    "Estadías",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        // Estadías activas
        mensaje.append("=== Estadías activas ===\n");
        if (activas != null && !activas.isEmpty()) {
            for (Estadia e : activas) {
                mensaje.append("ID: ").append(e.getId())
                       .append(" | Habitación: ").append(e.getHabitacion().getNumero())
                       .append(" | ID reserva: ").append(e.getReservacion().getID())
                       .append(" | Servicios consumidos: ").append(e.getConsumoServiciosAdicionales().size())
                       .append("\n");
            }
        } else {
            mensaje.append("No hay estadías activas.\n");
        }

        mensaje.append("\n=== Estadías finalizadas (check-out) ===\n");
        if (finalizadas != null && !finalizadas.isEmpty()) {
            for (Estadia e : finalizadas) {
                mensaje.append("ID: ").append(e.getId())
                       .append(" | Habitación: ").append(e.getHabitacion().getNumero())
                       .append(" | ID reserva: ").append(e.getReservacion().getID())
                       .append(" | Costo hab.: ").append(e.getCostoHabitacion())
                       .append(" | Costo serv.: ").append(e.getCostoServicios())
                       .append(" | Total: ").append(e.getCostoTotal())
                       .append("\n");
            }
        } else {
            mensaje.append("No hay estadías finalizadas.\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Estadías registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarEstadiasActionPerformed

    private void btnMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEstadiasActionPerformed
        ArrayList<Reservacion> reservaciones = gestionarReservaciones.getReservaciones();

        if ((reservaciones == null || reservaciones.isEmpty())) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay reservaciones registradas.",
                    "Reservaciones",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Reservacion r : reservaciones) {
            mensaje.append("ID: ").append(r.getID()).append("\n")
                   .append("Fecha inicio: ").append(r.getFechaInicio()).append("\n")
                   .append("Fecha final: ").append(r.getFechaFinal()).append("\n")
                   .append("Duración: ").append(r.getDuracion()).append(" noches\n")
                   .append("Tipo habitación: ").append(r.getTipoHabitacion()).append("\n")
                   .append("Huésped responsable: ").append(r.getHuespedResponsable().getNombres())
                   .append(" ").append(r.getHuespedResponsable().getApellidos()).append("\n")
                   .append("DNI de huésped responsable: ").append(r.getHuespedResponsable().getDNI()).append(")\n")
                   .append("--------------------------\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Reservaciones registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarEstadiasActionPerformed

    private void btnMostrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEstadiasActionPerformed
        ArrayList<ServicioAdicional> servicios = gestionarServiciosAdicionales.getServiciosAdicionales();

        if ((servicios == null || servicios.isEmpty())) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay servicios adicionales registradas.",
                    "Servicios adicionales",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (ServicioAdicional r : servicios) {
            mensaje.append("ID: ").append(r.getID()).append("\n")
                   .append("Nombre: ").append(r.getNombre()).append("\n")
                   .append("Precio: ").append(r.getPrecio()).append("\n")
                   .append("--------------------------\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Reservaciones registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarEstadiasActionPerformed

    private void btnMostrarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEstadiasActionPerformed
        ArrayList<Habitacion> habitaciones = gestionarHabitaciones.getHabitaciones();

        if ((habitaciones == null || habitaciones.isEmpty())) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay habitaciones registradas.",
                    "Habitaciones",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder mensaje = new StringBuilder();

        for (Habitacion h : habitaciones) {
            mensaje.append("Número: ").append(h.getNumero())
                   .append(" | Tipo: ").append(h.getTipoHabitacion())
                   .append(" | Capacidad: ").append(h.getCapacidadMAX())
                   .append(" | Precio: ").append(h.getPrecioPorNoche())
                   .append(" | Estado: ").append(h.getEstadoHabitacion())
                   .append(" | Disponible: ").append(h.isDisponible())
                   .append("\n");
        }

        JOptionPane.showMessageDialog(
                this,
                mensaje.toString(),
                "Habitaciones registradas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnMostrarEstadiasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormularioEstadia();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarReservas;
    private javax.swing.JButton btnMostrarServicios;
    private javax.swing.JButton btnMostrarEstadias;
    private javax.swing.JButton btnMostrarHabitaciones;
    private javax.swing.JButton btnRegistrarConsumo;
    private javax.swing.JComboBox<String> cboEstadoHabitacion;
    private javax.swing.JLabel lblEstadoHabitacion;
    private javax.swing.JLabel lblIdEstadia;
    private javax.swing.JLabel lblIdReservacion;
    private javax.swing.JLabel lblIdServicio;
    private javax.swing.JLabel lblNumeroHabitacion;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEstadias;
    private javax.swing.JTextField txtIdEstadia;
    private javax.swing.JTextField txtIdReservacion;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtNumeroHabitacion;
    // End of variables declaration//GEN-END:variables
}
