/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Gestion.GestionarHabitaciones;
import Reportes.ReporteOcupacionHabitaciones;

/**
 *
 * @author 20240
 */
public class InterfazReporteOcupacion extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazReporteOcupacion
     */
    private GestionarHabitaciones gestionarHabitaciones;
    
    public InterfazReporteOcupacion(GestionarHabitaciones gestionarHabitaciones) {
        initComponents();
        this.gestionarHabitaciones = gestionarHabitaciones;

        setTitle("Reporte de Ocupación de Habitaciones");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOcupacion = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMostrarResumen = new javax.swing.JButton();
        btnMostrarDetalles = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitulo.setText("Reporte de ocupación de habitaciones");

        btnMostrarResumen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarResumen.setText("Mostrar resumen");
        btnMostrarResumen.addActionListener(this::btnMostrarResumenActionPerformed);

        btnMostrarDetalles.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarDetalles.setText("Mostrar detalles");
        btnMostrarDetalles.addActionListener(this::btnMostrarDetallesActionPerformed);

        btnCerrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnCerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnMostrarResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar))
        );

        txtAreaResultado.setEditable(false);
        txtAreaResultado.setColumns(20);
        txtAreaResultado.setLineWrap(true);
        txtAreaResultado.setRows(5);
        txtAreaResultado.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaResultado);

        javax.swing.GroupLayout panelOcupacionLayout = new javax.swing.GroupLayout(panelOcupacion);
        panelOcupacion.setLayout(panelOcupacionLayout);
        panelOcupacionLayout.setHorizontalGroup(
            panelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOcupacionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelOcupacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelOcupacionLayout.setVerticalGroup(
            panelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOcupacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarResumenActionPerformed
        ReporteOcupacionHabitaciones reporte = new ReporteOcupacionHabitaciones(gestionarHabitaciones);
                
        String texto = reporte.resumenOcupacion();
        txtAreaResultado.setText(texto);
    }//GEN-LAST:event_btnMostrarResumenActionPerformed

    private void btnMostrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDetallesActionPerformed
        ReporteOcupacionHabitaciones reporte = new ReporteOcupacionHabitaciones(gestionarHabitaciones);

        String texto = reporte.detallesOcupacion();
        txtAreaResultado.setText(texto);    
    }//GEN-LAST:event_btnMostrarDetallesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMostrarDetalles;
    private javax.swing.JButton btnMostrarResumen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelOcupacion;
    private javax.swing.JTextArea txtAreaResultado;
    // End of variables declaration//GEN-END:variables
}
