/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Gestion.Autenticacion;
import Gestion.GestionarEmpleados;
import Personas.Empleado;
import javax.swing.JOptionPane;
import Gestion.GestionarHabitaciones;
import Gestion.GestionarHuespedes;
import Gestion.GestionarServiciosAdicionales;
import Gestion.GestionarReservaciones;
import Gestion.GestionarEstadias;

/**
 *
 * @author 20240
 */
public class InterfazOperador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazOperador.class.getName());

    
    private GestionarEmpleados gestionarEmpleados;
    private Autenticacion autenticacion;
    private GestionarHabitaciones gestionarHabitaciones;
    private GestionarServiciosAdicionales gestionarServiciosAdicionales;
    private GestionarHuespedes gestionarHuespedes;
    private GestionarReservaciones gestionarReservaciones;
    private GestionarEstadias gestionarEstadias;
    /**
     * Creates new form InterfazUsuario
     */
    public InterfazOperador() {
        initComponents();
 
        setLocationRelativeTo(null);
        
        setSize(345, 250);
        setResizable(false);
        
        gestionarEmpleados = new GestionarEmpleados();
        autenticacion = new Autenticacion();
        
        Empleado admin = new Empleado("20240599", "Mauricio", "Camones", "admin", "1234", true);
        gestionarEmpleados.agregar(admin);
        
        Empleado recep = new Empleado("20240488", "Fabrizio", "Brambilla", "recep", "1234", false);
        gestionarEmpleados.agregar(recep);
        
        panelMenu.setVisible(false);
        
        gestionarHabitaciones = new GestionarHabitaciones();
        gestionarServiciosAdicionales = new GestionarServiciosAdicionales();
        gestionarHuespedes = new GestionarHuespedes();
        gestionarReservaciones = new GestionarReservaciones();
        gestionarEstadias = new GestionarEstadias();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnGestionHuespedes = new javax.swing.JButton();
        btnGestionHabitaciones = new javax.swing.JButton();
        btnGestionReservaciones = new javax.swing.JButton();
        btnGestionEstadias = new javax.swing.JButton();
        btnGestionServicios = new javax.swing.JButton();
        btnGestionEmpleados = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnReporteIngresos = new javax.swing.JButton();
        btnReporteOcupacion = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Gestionar Estadias");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBienvenido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBienvenido.setText("¡Bienvenido!");
        lblBienvenido.setToolTipText("");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        lblContrasena.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblContrasena.setText("Contraseña:");

        txtContrasena.addActionListener(this::txtContrasenaActionPerformed);

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLogin.setText("Iniciar Sesión");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasena))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenido)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnGestionHuespedes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionHuespedes.setText("Gestionar Huespedes");
        btnGestionHuespedes.addActionListener(this::btnGestionHuespedesActionPerformed);

        btnGestionHabitaciones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionHabitaciones.setText("Gestionar Habitaciones");
        btnGestionHabitaciones.addActionListener(this::btnGestionHabitacionesActionPerformed);

        btnGestionReservaciones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionReservaciones.setText("Gestionar Reservaciones");
        btnGestionReservaciones.addActionListener(this::btnGestionReservacionesActionPerformed);

        btnGestionEstadias.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionEstadias.setText("Gestionar Estadias");
        btnGestionEstadias.addActionListener(this::btnGestionEstadiasActionPerformed);

        btnGestionServicios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionServicios.setText("Gestionar Servicios Adicionales");
        btnGestionServicios.addActionListener(this::btnGestionServiciosActionPerformed);

        btnGestionEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGestionEmpleados.setText("Gestionar Empleados");
        btnGestionEmpleados.addActionListener(this::btnGestionEmpleadosActionPerformed);

        btnCerrarSesion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        btnReporteIngresos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReporteIngresos.setText("Reporte de Ingresos");
        btnReporteIngresos.addActionListener(this::btnReporteIngresosActionPerformed);

        btnReporteOcupacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReporteOcupacion.setText("Reporte de Ocupación");
        btnReporteOcupacion.addActionListener(this::btnReporteOcupacionActionPerformed);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGestionHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionReservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionEstadias, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addGap(89, 89, 89))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnGestionEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGestionHuespedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionReservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionEstadias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteOcupacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String usuario = txtUsuario.getText().trim();
        String contrasena = txtContrasena.getText().trim();

        Empleado empleadoLogueado = autenticacion.login(gestionarEmpleados.getEmpleados(), usuario, contrasena);

        if (empleadoLogueado != null) {

            String rol = empleadoLogueado.isAdmin() ? "Administrador" : "Recepcionista";

            JOptionPane.showMessageDialog(
                this,
                "=== ACCESO AL SISTEMA ===\n\n"
                + "Bienvenido(a): " + empleadoLogueado.getNombres() + " "
                + empleadoLogueado.getApellidos() + "\n"
                + "DNI: " + empleadoLogueado.getDNI() + "\n"
                + "Rol del usuario: " + rol + "\n\n"
                + "Estado: Acceso autorizado.\n"
                + "Ya puedes navegar por las funciones del sistema.",
                "Bienvenido",
                JOptionPane.INFORMATION_MESSAGE
        );

        jPanel1.setVisible(false);   
        panelMenu.setVisible(true);  

        pack();                    
        setLocationRelativeTo(null);

        boolean esAdmin = empleadoLogueado.isAdmin();

        btnGestionEmpleados.setVisible(esAdmin);
        btnGestionHabitaciones.setVisible(esAdmin);
        btnGestionServicios.setVisible(esAdmin);
        btnReporteIngresos.setVisible(esAdmin);
        btnReporteOcupacion.setVisible(esAdmin);

        btnGestionHuespedes.setVisible(!esAdmin);
        btnGestionReservaciones.setVisible(!esAdmin);
        btnGestionEstadias.setVisible(!esAdmin);

        btnCerrarSesion.setVisible(true);

    } else {
        JOptionPane.showMessageDialog(
            this,
            "Usuario o contraseña incorrectos",
            "Error de autenticacion",
            JOptionPane.ERROR_MESSAGE
        );
    }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
        InterfazGestionEmpleados ventana = new InterfazGestionEmpleados(gestionarEmpleados);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void btnGestionServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionServiciosActionPerformed
        InterfazGestionServicios ventana = new InterfazGestionServicios(gestionarServiciosAdicionales);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);  
    }//GEN-LAST:event_btnGestionServiciosActionPerformed

    private void btnGestionHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionHabitacionesActionPerformed
        InterfazGestionHabitaciones ventanaHab = new InterfazGestionHabitaciones(gestionarHabitaciones);
        ventanaHab.setLocationRelativeTo(this);
        ventanaHab.setVisible(true);
    }//GEN-LAST:event_btnGestionHabitacionesActionPerformed

    private void btnGestionHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionHuespedesActionPerformed
        InterfazGestionHuespedes ventana = new InterfazGestionHuespedes(gestionarHuespedes);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionHuespedesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        panelMenu.setVisible(false);
        jPanel1.setVisible(true);
        
        txtUsuario.setText("");
        txtContrasena.setText("");
        
        setSize(345, 250);  
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnReporteIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresosActionPerformed
        InterfazReporteIngresos ventana = new InterfazReporteIngresos(gestionarEstadias);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReporteIngresosActionPerformed

    private void btnGestionReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionReservacionesActionPerformed
        InterfazGestionReservaciones ventana = new InterfazGestionReservaciones(
                gestionarReservaciones,
                gestionarHuespedes);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionReservacionesActionPerformed

    private void btnGestionEstadiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEstadiasActionPerformed
        InterfazGestionEstadias ventana = new InterfazGestionEstadias(gestionarEstadias, 
                gestionarReservaciones, 
                gestionarHabitaciones, 
                gestionarServiciosAdicionales);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionEstadiasActionPerformed

    private void btnReporteOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteOcupacionActionPerformed
        InterfazReporteOcupacion ventana = new InterfazReporteOcupacion(gestionarHabitaciones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReporteOcupacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazOperador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btnGestionEstadias;
    private javax.swing.JButton btnGestionHabitaciones;
    private javax.swing.JButton btnGestionHuespedes;
    private javax.swing.JButton btnGestionReservaciones;
    private javax.swing.JButton btnGestionServicios;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReporteIngresos;
    private javax.swing.JButton btnReporteOcupacion;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
